# Generated by Django 3.1.1 on 2020-10-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_event_event_list_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_list',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.event'),
        ),
        migrations.AddField(
            model_name='event_list',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.visitor'),
        ),
    ]
