# Generated by Django 3.1.1 on 2020-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201018_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_list',
            name='tag',
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
