# Generated by Django 3.1.1 on 2020-10-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_event_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_List',
            new_name='Ticket',
        ),
    ]
