# Generated by Django 3.1.1 on 2020-10-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201019_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='visitor',
            new_name='visitors',
        ),
    ]
