# Generated by Django 3.1.1 on 2020-10-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201020_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='visitors',
            new_name='visitor',
        ),
    ]
