# Generated by Django 3.1.1 on 2020-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201020_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
