# Generated by Django 3.1.1 on 2020-10-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201020_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visitor',
            field=models.ManyToManyField(null=True, to='accounts.Visitor'),
        ),
    ]
