# Generated by Django 3.1.1 on 2020-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_event_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='visitor',
            field=models.ManyToManyField(to='accounts.Visitor'),
        ),
    ]
