# Generated by Django 3.1.1 on 2020-10-18 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('end_date', models.DateTimeField(verbose_name='ending date')),
            ],
            options={
                'ordering': ['event_name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone_num', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InformationVisitor',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eve_holder.event')),
                ('name', models.CharField(max_length=150)),
                ('phone_num', models.CharField(max_length=100)),
                ('optional', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ManyToManyField(to='eve_holder.Host'),
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_num', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('event_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_holder.event')),
                ('event_already_regis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_holder.informationvisitor')),
            ],
        ),
    ]
