# Generated by Django 3.1.2 on 2020-10-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationVisitor',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eve_holder.event')),
                ('name', models.CharField(max_length=150)),
                ('phone_num', models.CharField(max_length=100)),
                ('optional', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_name']},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='host',
            name='phone_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='phone_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='event_already_regis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_holder.informationvisitor'),
        ),
        migrations.DeleteModel(
            name='Information_visitor',
        ),
    ]
