# Generated by Django 3.1.2 on 2020-10-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
