# Generated by Django 3.1.2 on 2020-10-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0002_delete_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event_already_regis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_holder.informationvisitor')),
                ('event_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_holder.event')),
            ],
        ),
    ]
