# Generated by Django 3.1.2 on 2020-10-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0003_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
