# Generated by Django 3.1.2 on 2020-10-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0004_auto_20201019_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
