# Generated by Django 3.1.2 on 2020-10-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0005_auto_20201019_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150, null=True)),
                ('visitor_phone_num', models.CharField(max_length=100, null=True)),
                ('visitor_email', models.EmailField(max_length=100, null=True)),
                ('visitor_password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='event_already_regis',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='event_history',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='event_host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='host',
            name='email',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(null=True, verbose_name='ending date'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_pub_date',
            field=models.DateTimeField(null=True, verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='host_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='phone_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='InformationVisitor',
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
        migrations.AddField(
            model_name='visitor',
            name='event',
            field=models.ManyToManyField(to='eve_holder.Event'),
        ),
    ]
