# Generated by Django 3.1.2 on 2020-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve_holder', '0006_auto_20201019_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='host_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visitor_phone_num',
            new_name='phone_num',
        ),
    ]
